[font]
size = 10

[font.bold]
family = "JetBrains Mono"
style = "Medium"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.offset]
x = 0
y = 3

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[window.padding]
x = 10
y = 5

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#5a647e"
blue = "#6d9cbe"
cyan = "#519f50"
green = "#6fa612"
magenta = "#b6b3eb"
red = "#da4939"
white = "#f9f7f3"
yellow = "#ffc66d"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.dim]
black = "#2b2b2b"
blue = "#507fa0"
cyan = "#358438"
green = "#85a142"
magenta = "#8b89be"
red = "#bd3e30"
white = "#b4afaa"
yellow = "#cc9841"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "#2b2b2b"
blue = "#6d9cbe"
cyan = "#519f50"
green = "#65c10f"
magenta = "#b6b3eb"
red = "#da4939"
white = "#e6e1dc"
yellow = "#ffc66d"

[colors.primary]
background = "#191919"
foreground = "#efeae4"

[colors.search.focused_match]
background = "#ffb86c"
foreground = "#44475a"

[colors.search.matches]
background = "#50fa7b"
foreground = "#44475a"

[colors.selection]
background = "#44475a"
text = "CellForeground"